In [132]:
import pandas as pd
import numpy as np

In [208]:
df = pd.read_parquet("./tadawul_clean.parquet")

FileNotFoundError: [Errno 2] No such file or directory: './tadawul_clean.parquet'

In [209]:
groups=df[df["Ticker"] == "2222.SR"]

In [210]:
g = df.groupby("Ticker")

In [211]:
g.groups

{'1010.SR': [13, 86, 94, 154, 181, 227, 259, 307, 343, 411, 443, 497, 536, 565, 601, 642, 688, 726, 747, 789, 856, 873, 915, 986, 1031, 1089, 1124, 1154, 1188, 1240, 1264, 1312, 1350, 1394, 1433, 1490, 1531, 1553, 1604, 1627, 1677, 1744, 1772, 1792, 1858, 1903, 1924, 1980, 2021, 2046, 2111, 2130, 2173, 2205, 2277, 2285, 2357, 2385, 2418, 2460, 2498, 2555, 2608, 2635, 2657, 2707, 2765, 2787, 2856, 2887, 2899, 2958, 2991, 3032, 3086, 3120, 3175, 3206, 3220, 3298, 3320, 3363, 3391, 3426, 3476, 3532, 3547, 3624, 3668, 3693, 3733, 3777, 3825, 3860, 3886, 3937, 3983, 4031, 4057, 4102, ...], '1020.SR': [20, 46, 124, 131, 176, 240, 283, 319, 337, 389, 440, 473, 533, 568, 590, 643, 677, 708, 766, 819, 863, 887, 921, 1007, 1015, 1090, 1125, 1152, 1198, 1246, 1266, 1301, 1346, 1411, 1442, 1462, 1519, 1571, 1602, 1656, 1691, 1743, 1766, 1799, 1849, 1902, 1950, 1958, 2028, 2067, 2088, 2139, 2168, 2217, 2247, 2318, 2339, 2371, 2428, 2480, 2508, 2548, 2582, 2621, 2690, 2706, 2773, 2796, 2851, 2873, 2908, 2959, 2993, 3049, 3063, 3123, 3167, 3213, 3247, 3278, 3336, 3342, 3389, 3450, 3491, 3539, 3576, 3610, 3645, 3707, 3723, 3779, 3811, 3838, 3894, 3953, 3972, 4002, 4042, 4095, ...], '1030.SR': [17, 57, 90, 136, 198, 233, 280, 308, 347, 406, 450, 486, 534, 541, 592, 631, 696, 730, 762, 805, 848, 880, 927, 995, 1010, 1079, 1099, 1164, 1174, 1243, 1270, 1325, 1368, 1403, 1424, 1470, 1511, 1556, 1615, 1650, 1686, 1713, 1757, 1822, 1856, 1891, 1943, 1993, 2000, 2065, 2102, 2153, 2183, 2224, 2263, 2296, 2344, 2378, 2443, 2474, 2511, 2567, 2584, 2639, 2669, 2729, 2742, 2786, 2843, 2857, 2934, 2979, 2992, 3046, 3085, 3131, 3152, 3188, 3237, 3271, 3306, 3369, 3417, 3439, 3501, 3534, 3583, 3621, 3629, 3698, 3730, 3774, 3806, 3836, 3914, 3939, 3965, 4004, 4052, 4112, ...], '1050.SR': [21, 68, 92, 133, 187, 223, 288, 318, 364, 394, 454, 458, 515, 554, 585, 660, 700, 729, 752, 825, 843, 885, 922, 976, 1035, 1076, 1127, 1139, 1182, 1255, 1279, 1313, 1372, 1392, 1432, 1487, 1523, 1557, 1586, 1649, 1683, 1716, 1779, 1816, 1868, 1895, 1916, 1983, 2008, 2044, 2096, 2158, 2164, 2218, 2261, 2305, 2334, 2366, 2435, 2483, 2518, 2545, 2604, 2644, 2688, 2732, 2734, 2792, 2853, 2868, 2927, 2973, 2984, 3047, 3060, 3132, 3155, 3180, 3251, 3272, 3302, 3345, 3398, 3425, 3492, 3545, 3551, 3591, 3652, 3703, 3736, 3755, 3814, 3869, 3883, 3917, 3979, 3998, 4058, 4119, ...], '1060.SR': [9, 83, 98, 132, 191, 214, 273, 313, 360, 378, 430, 464, 528, 577, 612, 637, 679, 704, 757, 797, 864, 874, 935, 971, 1047, 1065, 1097, 1146, 1212, 1230, 1292, 1317, 1376, 1400, 1447, 1477, 1503, 1580, 1607, 1628, 1692, 1705, 1759, 1825, 1847, 1871, 1939, 1976, 2019, 2060, 2091, 2133, 2180, 2221, 2272, 2321, 2354, 2394, 2419, 2479, 2496, 2539, 2598, 2641, 2692, 2708, 2741, 2814, 2841, 2883, 2898, 2949, 3020, 3025, 3070, 3108, 3150, 3203, 3231, 3297, 3325, 3357, 3402, 3443, 3466, 3537, 3570, 3618, 3631, 3676, 3737, 3764, 3827, 3855, 3903, 3950, 3976, 4027, 4056, 4113, ...], '1080.SR': [6, 49, 89, 152, 180, 218, 263, 329, 349, 381, 434, 468, 523, 578, 586, 658, 676, 710, 779, 816, 865, 876, 942, 997, 1041, 1053, 1123, 1144, 1190, 1216, 1285, 1321, 1352, 1383, 1438, 1483, 1524, 1558, 1585, 1647, 1669, 1720, 1782, 1805, 1854, 1889, 1940, 1982, 2010, 2052, 2084, 2152, 2174, 2204, 2258, 2292, 2350, 2375, 2429, 2455, 2507, 2534, 2573, 2627, 2653, 2724, 2762, 2794, 2855, 2876, 2919, 2948, 3018, 3034, 3073, 3106, 3138, 3199, 3230, 3285, 3328, 3376, 3405, 3437, 3498, 3520, 3577, 3601, 3634, 3679, 3747, 3752, 3830, 3850, 3889, 3919, 3977, 4014, 4072, 4097, ...], '1111.SR': [22, 50, 118, 143, 196, 222, 281, 310, 362, 379, 446, 477, 532, 550, 606, 625, 668, 731, 783, 793, 859, 896, 934, 985, 1048, 1060, 1126, 1148, 1211, 1250, 1294, 1344, 1415, 1426, 1478, 1514, 1573, 1590, 1635, 1682, 1736, 1776, 1796, 1840, 1892, 1928, 1967, 2036, 2039, 2109, 2120, 2184, 2227, 2276, 2306, 2336, 2401, 2408, 2487, 2500, 2536, 2589, 2638, 2664, 2728, 2760, 2791, 2822, 2893, 2923, 2951, 2980, 3083, 3113, 3148, 3211, 3219, 3291, 3322, 3348, 3403, 3444, 3468, 3529, 3555, 3625, 3666, 3673, 3729, 3758, 3815, 3844, 3884, 3938, 3995, 4025, 4054, 4116, 4143, 4164, ...], '1120.SR': [42, 85, 87, 158, 195, 216, 277, 315, 371, 377, 451, 489, 501, 552, 616, 624, 699, 733, 784, 803, 845, 883, 918, 994, 1045, 1052, 1115, 1171, 1178, 1221, 1284, 1329, 1359, 1377, 1457, 1496, 1518, 1549, 1594, 1644, 1671, 1718, 1747, 1811, 1833, 1896, 1922, 1960, 2031, 2038, 2100, 2123, 2186, 2211, 2275, 2311, 2337, 2367, 2416, 2482, 2524, 2557, 2605, 2637, 2673, 2718, 2750, 2784, 2832, 2872, 2932, 2968, 3007, 3028, 3075, 3122, 3160, 3215, 3240, 3268, 3332, 3371, 3415, 3424, 3494, 3517, 3566, 3600, 3658, 3702, 3716, 3790, 3797, 3846, 3881, 3924, 3987, 4026, 4073, 4117, ...], '1140.SR': [38, 55, 117, 168, 173, 219, 271, 296, 370, 386, 449, 492, 530, 547, 614, 659, 678, 740, 771, 806, 838, 900, 924, 1002, 1027, 1054, 1113, 1151, 1179, 1218, 1259, 1332, 1364, 1379, 1418, 1466, 1535, 1567, 1601, 1640, 1674, 1709, 1777, 1817, 1830, 1884, 1923, 1974, 2018, 2054, 2114, 2128, 2177, 2220, 2273, 2291, 2355, 2377, 2423, 2467, 2490, 2556, 2601, 2631, 2682, 2701, 2739, 2801, 2834, 2897, 2936, 2961, 2997, 3021, 3068, 3107, 3144, 3207, 3235, 3260, 3331, 3367, 3400, 3440, 3478, 3525, 3582, 3617, 3638, 3680, 3726, 3770, 3800, 3853, 3898, 3936, 3968, 4033, 4060, 4081, ...], '1150.SR': [35, 81, 97, 159, 197, 232, 284, 323, 354, 391, 441, 476, 500, 567, 600, 627, 682, 721, 777, 826, 831, 901, 923, 987, 1009, 1072, 1100, 1169, 1200, 1223, 1278, 1300, 1371, 1398, 1428, 1472, 1532, 1552, 1616, 1652, 1687, 1711, 1755, 1807, 1844, 1875, 1941, 1969, 2005, 2059, 2118, 2148, 2189, 2228, 2246, 2303, 2333, 2387, 2437, 2485, 2520, 2542, 2602, 2648, 2671, 2721, 2744, 2783, 2847, 2871, 2906, 2967, 2982, 3044, 3094, 3130, 3149, 3191, 3248, 3279, 3314, 3358, 3422, 3453, 3487, 3507, 3562, 3613, 3649, 3694, 3732, 3766, 3804, 3862, 3907, 3943, 3969, 4003, 4044, 4093, ...], '1180.SR': [32, 65, 121, 149, 209, 212, 253, 294, 348, 410, 437, 466, 513, 555, 594, 639, 694, 712, 767, 818, 849, 891, 950, 980, 1038, 1088, 1120, 1141, 1205, 1239, 1275, 1303, 1366, 1397, 1444, 1473, 1540, 1542, 1618, 1633, 1696, 1732, 1756, 1801, 1843, 1877, 1937, 1957, 2029, 2061, 2086, 2140, 2196, 2230, 2251, 2319, 2349, 2386, 2438, 2481, 2494, 2550, 2593, 2628, 2675, 2697, 2768, 2785, 2854, 2874, 2901, 2970, 2998, 3029, 3059, 3134, 3137, 3208, 3253, 3265, 3317, 3361, 3392, 3457, 3472, 3511, 3573, 3609, 3641, 3677, 3727, 3769, 3798, 3847, 3901, 3942, 3963, 4034, 4053, 4088, ...], '1211.SR': [29, 62, 119, 129, 179, 247, 289, 309, 363, 400, 420, 484, 505, 545, 605, 628, 667, 714, 782, 821, 847, 881, 944, 965, 974, 1034, 1074, 1095, 1140, 1181, 1244, 1276, 1298, 1357, 1405, 1458, 1481, 1520, 1550, 1595, 1654, 1681, 1707, 1774, 1826, 1837, 1890, 1946, 1977, 2009, 2049, 2116, 2154, 2165, 2212, 2253, 2308, 2326, 2398, 2440, 2450, 2506, 2547, 2574, 2630, 2666, 2719, 2769, 2811, 2824, 2870, 2915, 2939, 3003, 3037, 3079, 3101, 3159, 3200, 3242, 3273, 3304, 3377, 3393, 3463, 3490, 3516, 3578, 3589, 3644, 3675, 3750, 3767, 3794, 3864, 3902, 3916, 3980, 4016, 4040, ...], '1303.SR': [25, 61, 103, 148, 174, 215, 275, 314, 368, 392, 455, 474, 512, 544, 608, 629, 689, 743, 745, 812, 852, 872, 937, 982, 1039, 1075, 1117, 1145, 1196, 1254, 1268, 1293, 1358, 1378, 1449, 1498, 1500, 1560, 1608, 1663, 1665, 1719, 1750, 1812, 1828, 1909, 1932, 1986, 2035, 2058, 2104, 2122, 2193, 2214, 2269, 2312, 2328, 2404, 2421, 2452, 2491, 2562, 2578, 2636, 2686, 2727, 2749, 2812, 2842, 2860, 2911, 2969, 2995, 3041, 3080, 3098, 3158, 3197, 3243, 3295, 3324, 3380, 3419, 3427, 3505, 3522, 3586, 3590, 3647, 3689, 3742, 3765, 3802, 3839, 3878, 3952, 3996, 4012, 4055, 4114, ...], '2010.SR': [45, 52, 120, 155, 203, 228, 255, 298, 373, 395, 429, 498, 499, 548, 597, 651, 697, 719, 760, 807, 840, 889, 933, 958, 1008, 1040, 1062, 1121, 1138, 1202, 1248, 1282, 1331, 1367, 1387, 1440, 1469, 1526, 1575, 1588, 1648, 1695, 1715, 1775, 1803, 1832, 1901, 1935, 1984, 2023, 2042, 2105, 2137, 2162, 2215, 2268, 2288, 2360, 2390, 2407, 2457, 2526, 2543, 2610, 2633, 2683, 2704, 2770, 2795, 2820, 2882, 2913, 2962, 3013, 3022, 3077, 3116, 3156, 3205, 3246, 3293, 3340, 3350, 3420, 3428, 3502, 3523, 3550, 3603, 3664, 3684, 3746, 3772, 3809, 3873, 3913, 3921, 3994, 4010, 4078, ...], '2020.SR': [26, 77, 99, 160, 186, 220, 285, 317, 369, 393, 453, 467, 517, 563, 619, 657, 702, 738, 759, 813, 837, 906, 940, 963, 975, 1028, 1068, 1111, 1158, 1185, 1227, 1261, 1299, 1360, 1389, 1448, 1494, 1508, 1563, 1613, 1637, 1678, 1733, 1763, 1800, 1867, 1907, 1933, 1978, 2015, 2051, 2115, 2124, 2195, 2202, 2278, 2295, 2348, 2399, 2425, 2454, 2514, 2559, 2577, 2645, 2670, 2726, 2747, 2805, 2848, 2866, 2904, 2965, 3019, 3043, 3061, 3126, 3141, 3189, 3252, 3288, 3305, 3356, 3416, 3462, 3483, 3513, 3565, 3602, 3630, 3695, 3741, 3778, 3833, 3859, 3882, 3923, 3991, 4006, 4045, ...], '2082.SR': [27, 79, 110, 157, 172, 238, 286, 300, 367, 415, 445, 495, 529, 556, 618, 653, 671, 734, 778, 796, 844, 886, 912, 1006, 1043, 1078, 1098, 1167, 1175, 1242, 1306, 1348, 1386, 1451, 1485, 1507, 1544, 1617, 1662, 1664, 1717, 1752, 1814, 1860, 1899, 1929, 1959, 2002, 2066, 2101, 2155, 2194, 2216, 2248, 2304, 2338, 2369, 2431, 2472, 2517, 2551, 2571, 2618, 2680, 2715, 2736, 2797, 2818, 2861, 2914, 2978, 2986, 3072, 3104, 3162, 3179, 3238, 3266, 3308, 3373, 3384, 3459, 3489, 3515, 3561, 3614, 3655, 3710, 3735, 3753, 3832, 3871, 3890, 3948, 3992, 4037, 4039, 4098, 4142, 4166, ...], '2222.SR': [1, 3, 28, 58, 91, 161, 182, 210, 261, 330, 334, 351, 405, 439, 472, 519, 572, 581, 654, 681, 723, 758, 809, 860, 902, 911, 948, 953, 961, 966, 1004, 1029, 1066, 1094, 1136, 1204, 1233, 1289, 1327, 1334, 1353, 1409, 1437, 1499, 1516, 1574, 1598, 1639, 1675, 1731, 1784, 1794, 1842, 1894, 1910, 1913, 1926, 1990, 2004, 2070, 2080, 2149, 2190, 2203, 2264, 2314, 2363, 2383, 2446, 2466, 2515, 2564, 2583, 2619, 2665, 2710, 2764, 2807, 2846, 2879, 2910, 2955, 2987, 3054, 3081, 3118, 3143, 3181, 3256, 3264, 3341, 3351, 3396, 3448, 3481, 3524, 3569, 3599, 3648, 3696, ...], '2223.SR': [30, 71, 113, 139, 189, 248, 264, 326, 339, 385, 448, 480, 525, 564, 584, 623, 693, 741, 770, 795, 833, 903, 936, 962, 983, 1046, 1085, 1122, 1143, 1176, 1238, 1308, 1341, 1404, 1434, 1467, 1525, 1554, 1589, 1651, 1690, 1714, 1780, 1806, 1839, 1872, 1942, 1956, 2027, 2074, 2092, 2136, 2160, 2213, 2266, 2323, 2347, 2382, 2409, 2476, 2504, 2554, 2599, 2632, 2674, 2693, 2738, 2808, 2840, 2892, 2903, 2940, 3015, 3074, 3102, 3172, 3216, 3239, 3267, 3312, 3372, 3411, 3451, 3470, 3527, 3580, 3627, 3646, 3672, 3724, 3775, 3808, 3863, 3891, 3955, 3971, 4032, 4049, 4091, 4136, ...], '2280.SR': [31, 51, 116, 138, 199, 236, 252, 322, 355, 390, 426, 487, 508, 543, 610, 626, 701, 722, 780, 802, 854, 882, 914, 999, 1049, 1058, 1109, 1163, 1187, 1220, 1290, 1296, 1361, 1402, 1430, 1474, 1501, 1546, 1606, 1660, 1698, 1724, 1758, 1820, 1846, 1885, 1938, 1994, 2022, 2041, 2090, 2132, 2170, 2235, 2274, 2315, 2330, 2402, 2410, 2486, 2492, 2544, 2597, 2640, 2667, 2696, 2735, 2777, 2837, 2888, 2900, 2966, 3000, 3030, 3056, 3125, 3169, 3214, 3255, 3284, 3311, 3364, 3387, 3464, 3477, 3528, 3554, 3623, 3669, 3701, 3712, 3791, 3816, 3852, 3877, 3920, 3989, 4011, 4079, 4090, ...], '2290.SR': [34, 64, 123, 142, 204, 231, 260, 302, 357, 397, 421, 494, 516, 542, 602, 655, 669, 739, 763, 817, 846, 875, 930, 959, 970, 1032, 1070, 1103, 1135, 1189, 1215, 1283, 1323, 1365, 1396, 1435, 1459, 1536, 1581, 1592, 1630, 1688, 1734, 1785, 1789, 1865, 1880, 1947, 1962, 1996, 2037, 2093, 2145, 2167, 2241, 2249, 2289, 2364, 2380, 2445, 2468, 2521, 2568, 2590, 2643, 2668, 2711, 2754, 2779, 2830, 2895, 2922, 2960, 2994, 3026, 3095, 3115, 3154, 3217, 3244, 3276, 3321, 3346, 3395, 3432, 3467, 3508, 3568, 3611, 3636, 3704, 3725, 3773, 3805, 3837, 3906, 3918, 3993, 4024, 4074, ...], '2310.SR': [43, 78, 108, 167, 200, 237, 258, 297, 340, 382, 456, 491, 521, 558, 591, 656, 670, 713, 765, 798, 836, 892, 932, 956, 993, 1022, 1083, 1096, 1150, 1184, 1226, 1262, 1297, 1337, 1391, 1454, 1489, 1530, 1548, 1610, 1636, 1679, 1735, 1753, 1802, 1835, 1897, 1948, 1971, 2012, 2056, 2108, 2125, 2178, 2222, 2254, 2309, 2325, 2392, 2434, 2471, 2527, 2561, 2587, 2626, 2655, 2720, 2771, 2789, 2852, 2858, 2907, 2963, 3010, 3045, 3088, 3121, 3173, 3201, 3233, 3281, 3318, 3382, 3407, 3435, 3504, 3506, 3556, 3615, 3661, 3688, 3722, 3757, 3819, 3866, 3885, 3941, 3986, 4023, 4061, ...], '2380.SR': [36, 69, 122, 134, 175, 243, 276, 311, 344, 376, 438, 469, 507, 576, 589, 634, 684, 718, 749, 824, 862, 904, 928, 964, 978, 1011, 1067, 1110, 1162, 1210, 1229, 1274, 1314, 1349, 1413, 1423, 1480, 1529, 1565, 1587, 1629, 1702, 1710, 1764, 1810, 1845, 1898, 1951, 1968, 2014, 2072, 2113, 2121, 2188, 2225, 2281, 2300, 2342, 2372, 2417, 2478, 2499, 2565, 2585, 2616, 2691, 2714, 2752, 2775, 2826, 2859, 2925, 2945, 3014, 3040, 3092, 3096, 3170, 3198, 3232, 3261, 3323, 3347, 3406, 3445, 3479, 3509, 3549, 3604, 3665, 3685, 3738, 3784, 3803, 3851, 3912, 3949, 3981, 4020, 4043, ...], '2382.SR': [7088, 7157, 7184, 7221, 7278, 7336, 7365, 7411, 7422, 7474, 7541, 7560, 7594, 7637, 7676, 7741, 7768, 7837, 7865, 7896, 7939, 7976, 8017, 8072, 8132, 8181, 8200, 8265, 8295, 8358, 8401, 8410, 8448, 8496, 8542, 8587, 8637, 8698, 8720, 8759, 8825, 8837, 8886, 8933, 8972, 9034, 9074, 9133, 9145, 9183, 9221, 9297, 9332, 9387, 9394, 9408, 9438, 9513, 9560, 9579, 9628, 9658, 9712, 9766, 9821, 9862, 9896, 9938, 9992, 10017, 10061, 10122, 10129, 10200, 10238, 10278, 10326, 10373, 10393, 10467, 10499, 10539, 10575, 10604, 10642, 10675, 10714, 10738, 10815, 10832, 10877, 10934, 10955, 11026, 11069, 11098, 11117, 11171, 11215, 11264, ...], '4002.SR': [37, 48, 100, 163, 185, 225, 251, 325, 353, 396, 444, 488, 509, 546, 609, 646, 695, 728, 753, 810, 839, 893, 938, 972, 1033, 1061, 1129, 1137, 1186, 1251, 1281, 1330, 1356, 1380, 1421, 1482, 1527, 1559, 1582, 1643, 1684, 1726, 1746, 1809, 1859, 1888, 1944, 1964, 2030, 2063, 2098, 2142, 2200, 2229, 2270, 2307, 2327, 2405, 2413, 2448, 2519, 2541, 2591, 2646, 2681, 2695, 2737, 2778, 2839, 2890, 2937, 2943, 3001, 3023, 3078, 3135, 3168, 3204, 3234, 3280, 3326, 3365, 3386, 3434, 3474, 3526, 3553, 3588, 3663, 3706, 3718, 3782, 3810, 3861, 3908, 3927, 3967, 4007, 4067, 4092, ...], '4013.SR': [39, 67, 104, 150, 178, 235, 274, 312, 346, 402, 457, 481, 504, 559, 593, 641, 674, 716, 774, 822, 853, 898, 945, 1003, 1020, 1071, 1132, 1133, 1214, 1231, 1287, 1315, 1340, 1416, 1429, 1495, 1509, 1568, 1583, 1624, 1672, 1739, 1773, 1787, 1862, 1879, 1915, 1955, 2003, 2068, 2079, 2146, 2182, 2236, 2243, 2297, 2352, 2373, 2439, 2463, 2501, 2558, 2570, 2649, 2652, 2730, 2756, 2793, 2831, 2896, 2928, 2952, 3012, 3048, 3069, 3110, 3146, 3202, 3222, 3282, 3329, 3375, 3410, 3436, 3497, 3519, 3584, 3597, 3650, 3697, 3743, 3760, 3813, 3843, 3911, 3926, 3960, 3999, 4070, 4103, ...], '4030.SR': [40, 53, 95, 164, 201, 224, 282, 316, 359, 409, 436, 478, 539, 571, 588, 644, 664, 735, 772, 787, 857, 884, 917, 955, 988, 1036, 1082, 1093, 1165, 1203, 1252, 1280, 1302, 1374, 1401, 1450, 1476, 1506, 1579, 1605, 1623, 1697, 1745, 1748, 1815, 1850, 1873, 1919, 1975, 2017, 2057, 2082, 2127, 2166, 2240, 2250, 2313, 2362, 2370, 2414, 2459, 2495, 2569, 2572, 2620, 2658, 2722, 2763, 2809, 2816, 2864, 2938, 2974, 3004, 3042, 3055, 3124, 3164, 3186, 3227, 3292, 3315, 3366, 3401, 3458, 3488, 3514, 3557, 3612, 3656, 3682, 3734, 3761, 3828, 3848, 3909, 3947, 3964, 4030, 4050, ...], '4142.SR': [41, 72, 106, 165, 207, 229, 254, 328, 336, 412, 433, 475, 502, 580, 611, 622, 673, 737, 746, 792, 855, 870, 939, 998, 1025, 1055, 1116, 1173, 1207, 1245, 1328, 1373, 1382, 1441, 1484, 1528, 1569, 1619, 1625, 1685, 1738, 1768, 1818, 1831, 1882, 1914, 1979, 2020, 2050, 2112, 2129, 2175, 2237, 2262, 2301, 2340, 2384, 2420, 2484, 2493, 2531, 2607, 2624, 2659, 2723, 2761, 2780, 2828, 2885, 2931, 2944, 3011, 3089, 3111, 3151, 3185, 3249, 3269, 3337, 3370, 3423, 3449, 3480, 3512, 3552, 3620, 3657, 3709, 3721, 3759, 3817, 3835, 3875, 3946, 3982, 4001, 4063, 4118, 4156, 4197, ...], '4164.SR': [24, 73, 112, 153, 169, 246, 287, 292, 361, 387, 425, 496, 520, 560, 603, 649, 683, 720, 761, 786, 866, 869, 926, 984, 1018, 1064, 1092, 1161, 1195, 1241, 1305, 1343, 1406, 1443, 1465, 1521, 1547, 1603, 1658, 1693, 1706, 1771, 1823, 1836, 1870, 1920, 1992, 2026, 2064, 2083, 2134, 2179, 2210, 2267, 2317, 2351, 2396, 2406, 2469, 2489, 2533, 2575, 2623, 2684, 2712, 2748, 2798, 2821, 2867, 2933, 2975, 3005, 3064, 3100, 3177, 3190, 3229, 3275, 3338, 3374, 3397, 3433, 3495, 3518, 3587, 3619, 3643, 3690, 3731, 3762, 3812, 3858, 3910, 3944, 3961, 4028, 4059, 4111, 4137, 4174, ...], '4190.SR': [23, 75, 109, 130, 206, 245, 267, 324, 342, 407, 435, 470, 511, 570, 617, 633, 687, 706, 781, 811, 829, 907, 925, 981, 1017, 1069, 1105, 1170, 1191, 1224, 1291, 1324, 1362, 1393, 1425, 1479, 1510, 1562, 1584, 1645, 1701, 1722, 1786, 1813, 1852, 1906, 1918, 1995, 1997, 2073, 2097, 2141, 2197, 2234, 2279, 2298, 2345, 2376, 2415, 2465, 2522, 2535, 2594, 2611, 2687, 2705, 2774, 2790, 2850, 2877, 2929, 2977, 3016, 3031, 3087, 3128, 3174, 3209, 3236, 3274, 3307, 3378, 3385, 3461, 3469, 3531, 3571, 3596, 3639, 3708, 3740, 3756, 3818, 3872, 3900, 3929, 3974, 4038, 4068, 4084, ...], '4200.SR': [14, 70, 115, 144, 192, 241, 279, 299, 335, 380, 452, 471, 535, 551, 599, 650, 703, 724, 755, 788, 841, 890, 919, 957, 989, 1021, 1051, 1106, 1166, 1183, 1253, 1277, 1307, 1338, 1408, 1427, 1486, 1534, 1564, 1622, 1641, 1703, 1727, 1751, 1790, 1841, 1878, 1949, 1966, 2033, 2062, 2078, 2126, 2192, 2223, 2242, 2320, 2343, 2379, 2441, 2473, 2513, 2530, 2595, 2612, 2676, 2709, 2745, 2806, 2844, 2880, 2920, 2956, 2989, 3027, 3082, 3112, 3157, 3218, 3221, 3300, 3327, 3349, 3409, 3446, 3465, 3510, 3559, 3628, 3653, 3671, 3719, 3783, 3807, 3868, 3899, 3930, 3970, 4036, 4066, ...], '4220.SR': [5, 82, 105, 135, 190, 239, 268, 320, 345, 383, 418, 485, 526, 540, 613, 645, 685, 717, 748, 804, 867, 895, 951, 991, 1044, 1056, 1104, 1160, 1201, 1225, 1272, 1326, 1347, 1412, 1446, 1460, 1515, 1578, 1591, 1642, 1689, 1740, 1778, 1798, 1848, 1900, 1952, 1991, 2034, 2077, 2087, 2144, 2171, 2219, 2259, 2290, 2353, 2397, 2432, 2458, 2488, 2532, 2580, 2642, 2660, 2731, 2759, 2815, 2817, 2889, 2918, 2950, 2999, 3053, 3071, 3109, 3140, 3196, 3226, 3289, 3335, 3379, 3404, 3441, 3499, 3521, 3572, 3608, 3667, 3691, 3711, 3776, 3801, 3840, 3896, 3931, 3959, 4013, 4064, 4115, ...], '4250.SR': [7, 76, 107, 162, 170, 242, 269, 293, 341, 413, 427, 460, 522, 569, 620, 661, 665, 744, 756, 791, 851, 868, 946, 992, 1023, 1086, 1114, 1155, 1177, 1247, 1269, 1295, 1345, 1390, 1455, 1491, 1502, 1561, 1612, 1626, 1673, 1742, 1754, 1795, 1861, 1905, 1945, 1965, 2013, 2045, 2099, 2143, 2198, 2207, 2265, 2310, 2324, 2393, 2412, 2449, 2509, 2538, 2606, 2617, 2679, 2713, 2766, 2813, 2833, 2869, 2905, 2964, 2996, 3052, 3058, 3133, 3171, 3195, 3245, 3283, 3319, 3355, 3421, 3429, 3473, 3530, 3581, 3595, 3640, 3674, 3751, 3754, 3822, 3857, 3876, 3933, 3975, 4015, 4071, 4100, ...], '4263.SR': [7721, 7797, 7823, 7877, 7891, 7956, 7995, 8018, 8061, 8115, 8182, 8216, 8250, 8306, 8326, 8389, 8445, 8486, 8498, 8570, 8590, 8636, 8697, 8710, 8761, 8830, 8866, 8912, 8935, 8969, 9028, 9075, 9093, 9175, 9198, 9225, 9267, 9331, 9372, 9393, 9412, 9476, 9495, 9534, 9599, 9623, 9663, 9707, 9779, 9819, 9836, 9876, 9921, 9996, 10035, 10073, 10124, 10139, 10169, 10235, 10279, 10332, 10348, 10409, 10450, 10476, 10535, 10586, 10601, 10643, 10644, 10708, 10769, 10786, 10818, 10892, 10905, 10957, 10988, 11034, 11079, 11159, 11188, 11206, 11277, 11308, 11367, 11379, 11438, 11491, 11509, 11548, 11590, 11629, 11658, 11679, 11751, 11791, 11828, 11865, ...], '4280.SR': [8, 80, 111, 156, 194, 244, 291, 304, 372, 404, 432, 462, 510, 575, 621, 652, 686, 715, 785, 823, 834, 899, 952, 973, 1042, 1077, 1107, 1168, 1194, 1236, 1286, 1319, 1375, 1381, 1452, 1463, 1513, 1572, 1596, 1634, 1666, 1729, 1781, 1791, 1829, 1893, 1934, 1981, 2032, 2069, 2103, 2138, 2181, 2209, 2282, 2294, 2331, 2389, 2411, 2451, 2512, 2537, 2609,

In [225]:
tickers = df.Ticker

In [228]:
tickers.unique()

<ArrowStringArray>
['7010.SR', '2222.SR', '2310.SR', '4200.SR', '2380.SR', '2020.SR', '1211.SR',
 '2010.SR', '4030.SR', '2290.SR', '1010.SR', '1030.SR', '7020.SR', '8010.SR',
 '1020.SR', '1050.SR', '5110.SR', '4190.SR', '4280.SR', '1180.SR', '2280.SR',
 '1150.SR', '1140.SR', '4002.SR', '4013.SR', '1120.SR', '8210.SR', '1080.SR',
 '4220.SR', '4250.SR', '1060.SR', '4300.SR', '8230.SR', '1303.SR', '2223.SR',
 '1111.SR', '4164.SR', '2082.SR', '6015.SR', '7202.SR', '4142.SR', '2382.SR',
 '4263.SR']
Length: 43, dtype: str

In [190]:
groups.head()

          Date   Ticker      Close       High        Low       Open     Volume
17  2023-01-01  2222.SR  24.662405  24.662405  24.434050  24.472109  1569087.0
67  2023-01-02  2222.SR  24.472111  24.738526  24.472111  24.738526  4693364.0
167 2023-01-04  2222.SR  24.129574  24.472108  24.015397  24.434049  4618455.0
217 2023-01-05  2222.SR  24.015398  24.129575  23.748983  24.129575  4797670.0
267 2023-01-08  2222.SR  23.977335  24.015395  23.901217  24.015395  2074569.0

In [ ]:
groups

,Date,Ticker,Close,High,Low,Open,Volume
0,2023-01-01,1010.SR,19.938663,20.158807,19.938663,20.064459,307379.0
1,2023-01-01,1020.SR,11.810729,11.859889,11.749279,11.749279,2260396.0
2,2023-01-01,1030.SR,11.832534,11.832534,11.750742,11.791639,141395.0
3,2023-01-01,1050.SR,16.675842,16.716714,16.451045,16.716714,165957.0
4,2023-01-01,1060.SR,32.377926,32.544180,32.128546,32.419489,188123.0
...,...,...,...,...,...,...,...
10336,2023-11-01,4263.SR,124.117409,128.984755,109.140943,109.140943,15957180.0
10386,2023-11-02,4263.SR,119.811691,126.176690,119.811691,125.240661,3520831.0
10436,2023-11-05,4263.SR,122.058144,123.368592,119.998883,119.998883,2380750.0
10486,2023-11-06,4263.SR,121.683754,123.181406,120.373319,122.245377,1221800.0
10536,2023-11-07,4263.SR,123.368576,125.240633,121.496519,124.304605,2297859.0

In [212]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33086 entries, 0 to 33085
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Ticker          33086 non-null  str
 1   Date            33086 non-null  datetime64[ms]
 2   Close           33086 non-null  float64
 3   High            33086 non-null  float64
 4   Low             33086 non-null  float64
 5   Open            33086 non-null  float64
 6   Volume          33086 non-null  float64
 7   Return          33086 non-null  float64
 8   ret_14days      33086 non-null  float64
 9   RSI             33086 non-null  float64
 10  Volatility_std  33086 non-null  float64
 11  ATR             33086 non-null  float64
 12  BB_width        33086 non-null  float64
 13  Target          33086 non-null  int64
dtypes: datetime64[ms](1), float64(11), int64(1), str(1)
memory usage: 3.8 MB

In [136]:
df.shape

(33903, 7)

In [137]:
df_p = df.copy()

In [138]:
df_p["Return"] = df_p.groupby("Ticker")["Close"].pct_change()

In [139]:
def get_rsi(prices, period=14):
    delta = prices.diff()
    gain = delta.clip(lower=0)
    loss = -1 * delta.clip(upper=0)
    ma_gain = gain.ewm(alpha=1/period, adjust=False).mean()
    ma_loss = loss.ewm(alpha=1/period, adjust=False).mean()
    rs = ma_gain / ma_loss
    return 100 - (100 / (1 + rs))

In [140]:
df_p["RSI"] = df_p.groupby("Ticker")["Close"].transform(lambda x: get_rsi(x))

In [141]:
df_p["ret_14days"] = df_p.groupby("Ticker")["Return"].transform(lambda x: x.rolling(14).mean().shift(1))

In [142]:
df_p.head()

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days
0,2023-01-01,1010.SR,19.938663,20.158807,19.938663,20.064459,307379.0,NaN,NaN,NaN
1,2023-01-01,1020.SR,11.810729,11.859889,11.749279,11.749279,2260396.0,NaN,NaN,NaN
2,2023-01-01,1030.SR,11.832534,11.832534,11.750742,11.791639,141395.0,NaN,NaN,NaN
3,2023-01-01,1050.SR,16.675842,16.716714,16.451045,16.716714,165957.0,NaN,NaN,NaN
4,2023-01-01,1060.SR,32.377926,32.544180,32.128546,32.419489,188123.0,NaN,NaN,NaN

In [143]:
df_p.head(100)

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days
0,2023-01-01,1010.SR,19.938663,20.158807,19.938663,20.064459,307379.0,NaN,NaN,NaN
1,2023-01-01,1020.SR,11.810729,11.859889,11.749279,11.749279,2260396.0,NaN,NaN,NaN
2,2023-01-01,1030.SR,11.832534,11.832534,11.750742,11.791639,141395.0,NaN,NaN,NaN
3,2023-01-01,1050.SR,16.675842,16.716714,16.451045,16.716714,165957.0,NaN,NaN,NaN
4,2023-01-01,1060.SR,32.377926,32.544180,32.128546,32.419489,188123.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
163,2023-01-04,1303.SR,0.840125,0.863422,0.840125,0.861304,3025875.0,-0.016529,92.125984,NaN
164,2023-01-04,2010.SR,76.525330,77.290584,76.525330,77.035497,1224387.0,0.000000,NaN,NaN
165,2023-01-04,2020.SR,115.051559,118.283345,114.566799,118.121758,1197393.0,-0.028649,38.234285,NaN
166,2023-01-04,2082.SR,157.323257,160.100724,156.728089,157.521647,362349.0,0.012771,100.000000,NaN
167,2023-01-04,2222.SR,24.129574,24.472108,24.015397,24.434049,4618455.0,-0.013997,0.000000,NaN

In [144]:
df_p["Volatility_std"] = df_p.groupby("Ticker")["Return"].transform(lambda x: x.rolling(14).std().shift(1))

In [145]:
def calculate_atr(df, period=14):
    high_low = df["High"] - df["Low"]
    high_close = (df["High"] - df["Close"].shift()).abs()
    low_close = (df["Low"] - df["Close"].shift()).abs()

    ranges = pd.concat([high_low, high_close, low_close], axis=1)
    true_range = ranges.max(axis=1)
    return true_range.ewm(alpha=1/period, adjust=False).mean()

In [146]:
df_p["ATR"] = df_p.groupby("Ticker", group_keys=False).apply(calculate_atr)

In [147]:
def calculate_bb_width(series, period=20):
    ma = series.rolling(period).mean()
    std = series.rolling(period).std()
    upper = ma + (std * 2)
    lower = ma - (std * 2)
    return (upper - lower) / ma

In [148]:
df_p["BB_width"] = df_p.groupby("Ticker")["Close"].transform(lambda x: calculate_bb_width(x))

In [149]:
df_p.head()

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
0,2023-01-01,1010.SR,19.938663,20.158807,19.938663,20.064459,307379.0,NaN,NaN,NaN,NaN,0.220144,NaN
1,2023-01-01,1020.SR,11.810729,11.859889,11.749279,11.749279,2260396.0,NaN,NaN,NaN,NaN,0.110610,NaN
2,2023-01-01,1030.SR,11.832534,11.832534,11.750742,11.791639,141395.0,NaN,NaN,NaN,NaN,0.081791,NaN
3,2023-01-01,1050.SR,16.675842,16.716714,16.451045,16.716714,165957.0,NaN,NaN,NaN,NaN,0.265669,NaN
4,2023-01-01,1060.SR,32.377926,32.544180,32.128546,32.419489,188123.0,NaN,NaN,NaN,NaN,0.415634,NaN

In [150]:
df_p.tail()

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
41743,2026-05-07,7020.SR,64.050003,64.699997,63.750000,64.699997,634721.0,0.004706,41.055825,-0.005425,0.015279,1.394885,0.089933
41744,2026-05-07,7202.SR,228.600006,230.000000,224.100006,224.100006,338655.0,0.026493,67.961923,0.000292,0.012050,4.601450,0.141348
41746,2026-05-07,8010.SR,141.800003,142.000000,137.100006,137.100006,563026.0,0.034282,66.650881,0.003034,0.024212,3.606551,0.103220
41747,2026-05-07,8210.SR,180.100006,182.199997,179.199997,181.500000,160534.0,-0.003872,50.677937,-0.001856,0.018997,5.110899,0.059246
41748,2026-05-07,8230.SR,106.800003,108.599998,106.800003,108.199997,147917.0,-0.010195,48.140905,-0.004437,0.018829,3.514110,0.085922

In [151]:
befor_dropna = len(df_p)

In [152]:
df_p.shape

(33903, 13)

In [153]:
df_p.isna().sum()

Date                0
Ticker              0
Close               0
High                0
Low                 0
Open                0
Volume              0
Return             43
RSI                47
ret_14days        645
Volatility_std    645
ATR                 0
BB_width          817
dtype: int64

In [154]:
df_p = df_p.dropna()

In [155]:
diffr = befor_dropna - len(df_p)
diffr

817

In [156]:
df_p.shape

(33086, 13)

In [157]:
df_p.isna().sum()

Date              0
Ticker            0
Close             0
High              0
Low               0
Open              0
Volume            0
Return            0
RSI               0
ret_14days        0
Volatility_std    0
ATR               0
BB_width          0
dtype: int64

In [158]:
df_p.head()

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
992,2023-01-26,7010.SR,29.853119,29.892976,29.813262,29.853119,1069232.0,0.000000,67.660082,-0.000269,0.005874,0.377712,0.026902
1017,2023-01-29,2222.SR,25.119112,25.157171,24.966874,24.966874,3784113.0,0.003039,45.449200,0.003127,0.005957,0.280434,0.065764
1042,2023-01-29,7010.SR,29.972694,29.972694,29.853124,29.972694,1083576.0,0.004005,69.439786,-0.000839,0.005379,0.359274,0.024960
1067,2023-01-30,2222.SR,25.119112,25.195230,24.966874,25.119112,6385128.0,0.000000,45.449200,0.002891,0.005885,0.276714,0.068820
1092,2023-01-30,7010.SR,29.853119,29.972689,29.693689,29.972689,2978910.0,-0.003989,65.554728,-0.000742,0.005459,0.353540,0.025132

In [159]:
df_p.tail()

,Date,Ticker,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
41743,2026-05-07,7020.SR,64.050003,64.699997,63.750000,64.699997,634721.0,0.004706,41.055825,-0.005425,0.015279,1.394885,0.089933
41744,2026-05-07,7202.SR,228.600006,230.000000,224.100006,224.100006,338655.0,0.026493,67.961923,0.000292,0.012050,4.601450,0.141348
41746,2026-05-07,8010.SR,141.800003,142.000000,137.100006,137.100006,563026.0,0.034282,66.650881,0.003034,0.024212,3.606551,0.103220
41747,2026-05-07,8210.SR,180.100006,182.199997,179.199997,181.500000,160534.0,-0.003872,50.677937,-0.001856,0.018997,5.110899,0.059246
41748,2026-05-07,8230.SR,106.800003,108.599998,106.800003,108.199997,147917.0,-0.010195,48.140905,-0.004437,0.018829,3.514110,0.085922

In [160]:
df_p["Target"] = (df_p.groupby("Ticker")["Close"].shift(-1) > df_p["Close"] * 1.01).astype(int)

In [161]:
df_p.info()

<class 'pandas.DataFrame'>
Index: 33086 entries, 992 to 41748
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            33086 non-null  datetime64[ms]
 1   Ticker          33086 non-null  str
 2   Close           33086 non-null  float64
 3   High            33086 non-null  float64
 4   Low             33086 non-null  float64
 5   Open            33086 non-null  float64
 6   Volume          33086 non-null  float64
 7   Return          33086 non-null  float64
 8   RSI             33086 non-null  float64
 9   ret_14days      33086 non-null  float64
 10  Volatility_std  33086 non-null  float64
 11  ATR             33086 non-null  float64
 12  BB_width        33086 non-null  float64
 13  Target          33086 non-null  int64
dtypes: datetime64[ms](1), float64(11), int64(1), str(1)
memory usage: 4.0 MB

In [162]:
n = int(len(df_p) * 0.8)
t = int(len(df_p) * 0.2)
X_train = df_p.head(n)
X_test = df_p.tail(t)
Y_train = X_train["Target"]
Y_test = X_test["Target"]
X_train = X_train.drop(columns=["Date","Ticker","Target"])
X_test = X_test.drop(columns=["Date","Ticker","Target"])

In [163]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

In [164]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=50,
    random_state=42,
    n_jobs=-1
)

In [165]:
model.fit(X_train,Y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=50, n_estimators=200,
                       n_jobs=-1, random_state=42)

In [166]:
proba = model.predict_proba(X_test)[:, 1]

In [167]:
roc = roc_auc_score(Y_test, proba)

In [168]:
roc

0.5853808403048775

In [169]:
model.feature_importances_

array([0.05138808, 0.05138733, 0.05234105, 0.05654316, 0.07752265,
       0.1194289 , 0.087984  , 0.08497632, 0.18892528, 0.09147665,
       0.13802659])

In [234]:
full_X = pd.concat([X_train,X_test])
full_Y = pd.concat([Y_train,Y_test])
full_X = full_X.drop(columns=["Open","High","Close","Low"])

In [235]:
full_X.head()

,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
992,1069232.0,0.000000,67.660082,-0.000269,0.005874,0.377712,0.026902
1017,3784113.0,0.003039,45.449200,0.003127,0.005957,0.280434,0.065764
1042,1083576.0,0.004005,69.439786,-0.000839,0.005379,0.359274,0.024960
1067,6385128.0,0.000000,45.449200,0.002891,0.005885,0.276714,0.068820
1092,2978910.0,-0.003989,65.554728,-0.000742,0.005459,0.353540,0.025132

In [173]:
full_X.tail()

,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
41743,64.050003,64.699997,63.750000,64.699997,634721.0,0.004706,41.055825,-0.005425,0.015279,1.394885,0.089933
41744,228.600006,230.000000,224.100006,224.100006,338655.0,0.026493,67.961923,0.000292,0.012050,4.601450,0.141348
41746,141.800003,142.000000,137.100006,137.100006,563026.0,0.034282,66.650881,0.003034,0.024212,3.606551,0.103220
41747,180.100006,182.199997,179.199997,181.500000,160534.0,-0.003872,50.677937,-0.001856,0.018997,5.110899,0.059246
41748,106.800003,108.599998,106.800003,108.199997,147917.0,-0.010195,48.140905,-0.004437,0.018829,3.514110,0.085922

In [236]:
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=50,
    random_state=42,
    n_jobs=-1
)

In [237]:
model.fit(full_X,full_Y)

RandomForestClassifier(max_depth=10, min_samples_leaf=50, n_estimators=200,
                       n_jobs=-1, random_state=42)

In [239]:
model.feature_names_in_

array(['Volume', 'Return', 'RSI', 'ret_14days', 'Volatility_std', 'ATR',
       'BB_width'], dtype=object)

In [238]:
import joblib

joblib.dump(model, "stock_price_model.joblib")

['stock_price_model.joblib']

In [179]:
df_p.columns

Index(['Date', 'Ticker', 'Close', 'High', 'Low', 'Open', 'Volume', 'Return',
       'RSI', 'ret_14days', 'Volatility_std', 'ATR', 'BB_width', 'Target'],
      dtype='str')

In [183]:
feature_cols = ['Close', 'High', 'Low', 'Open', 'Volume', 'Return','RSI', 'ret_14days','Volatility_std', 'ATR', 'BB_width']

In [184]:
full_X.head()

,Close,High,Low,Open,Volume,Return,RSI,ret_14days,Volatility_std,ATR,BB_width
992,29.853119,29.892976,29.813262,29.853119,1069232.0,0.000000,67.660082,-0.000269,0.005874,0.377712,0.026902
1017,25.119112,25.157171,24.966874,24.966874,3784113.0,0.003039,45.449200,0.003127,0.005957,0.280434,0.065764
1042,29.972694,29.972694,29.853124,29.972694,1083576.0,0.004005,69.439786,-0.000839,0.005379,0.359274,0.024960
1067,25.119112,25.195230,24.966874,25.119112,6385128.0,0.000000,45.449200,0.002891,0.005885,0.276714,0.068820
1092,29.853119,29.972689,29.693689,29.972689,2978910.0,-0.003989,65.554728,-0.000742,0.005459,0.353540,0.025132

In [185]:
import json
with open ("feature_cols.json", "w") as f:
    json.dump(feature_cols, f)

In [217]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score




def get_rsi(prices, period=14):
    delta = prices.diff()
    gain = delta.clip(lower=0)
    loss = -1 * delta.clip(upper=0)
    ma_gain = gain.ewm(alpha=1/period, adjust=False).mean()
    ma_loss = loss.ewm(alpha=1/period, adjust=False).mean()
    rs = ma_gain / ma_loss
    return 100 - (100 / (1 + rs))


def calculate_atr(df, period=14):
    high_low = df["High"] - df["Low"]
    high_close = (df["High"] - df["Close"].shift()).abs()
    low_close = (df["Low"] - df["Close"].shift()).abs()
    ranges = pd.concat([high_low, high_close,low_close], axis=1)
    true_range = ranges.max(axis=1)
    return true_range.ewm(alpha=1/period, adjust=False).mean()


def calculate_bb_width(series, period=20):
    ma = series.rolling(period).mean()
    std = series.rolling(period).std()
    upper = ma + (std * 2)
    lower = ma - (std * 2)
    return (upper - lower) / ma


def build_features(df:pd.DataFrame) -> pd.DataFrame:
    df["Return"] = df["Close"].pct_change()
    df["ret_14days"] = df["Return"].rolling(14).mean().shift(1)
    df["RSI"] = get_rsi(df["Close"])
    df["Volatility_std"] = df["Return"].rolling(14).std().shift(1)
    df["ATR"] = calculate_atr(df)
    df["BB_width"] = calculate_bb_width(df["Close"])
    df = df.dropna()
    return df




df = df.groupby("Ticker").apply(build_features)
df = df.reset_index(level="Ticker").sort_values("Date").reset_index(drop=True)
df["Target"] = (df.groupby("Ticker")["Close"].shift(-1) > df["Close"]).astype(int)

n = int(len(df) * 0.8)
t = int(len(df) * 0.2)
"""
X_train_new = df.head(n)
X_test_new = df.tail(t)
Y_train_new = X_train["Target"]
Y_test_new = X_test["Target"]
X_train_new = X_train.drop(columns=["Date","Ticker","Target",])
X_test_new = X_test.drop(columns=["Date","Ticker","Target",])

X_train_new
"""

'\nX_train_new = df.head(n)\nX_test_new = df.tail(t)\nY_train_new = X_train["Target"]\nY_test_new = X_test["Target"]\nX_train_new = X_train.drop(columns=["Date","Ticker","Target",])\nX_test_new = X_test.drop(columns=["Date","Ticker","Target",])\n\nX_train_new\n'

In [218]:
df.head()

,Ticker,Date,Close,High,Low,Open,Volume,Return,ret_14days,RSI,Volatility_std,ATR,BB_width,Target
0,7010.SR,2023-05-22,36.297256,36.500716,35.808954,35.890337,3169753.0,0.007909,0.000445,67.583952,0.015966,0.715008,0.062394,0
1,7010.SR,2023-05-23,35.849648,36.500719,35.727573,36.256567,4356466.0,-0.012332,0.001733,61.832175,0.015774,0.719161,0.060256,0
2,7010.SR,2023-05-24,35.564800,36.175180,35.320649,35.849643,3877533.0,-0.007946,0.003206,58.424550,0.013005,0.728830,0.059794,0
3,7010.SR,2023-05-25,34.710278,35.564809,34.710278,35.564809,5045620.0,-0.024027,0.001296,49.594433,0.012493,0.737809,0.063378,0
4,7010.SR,2023-05-28,33.774357,34.873039,33.611588,34.710274,4954284.0,-0.026964,-0.001491,42.090993,0.013513,0.775212,0.079169,0

In [219]:
X_train_new = df.head(n)

In [220]:
X_train_new.head()

,Ticker,Date,Close,High,Low,Open,Volume,Return,ret_14days,RSI,Volatility_std,ATR,BB_width,Target
0,7010.SR,2023-05-22,36.297256,36.500716,35.808954,35.890337,3169753.0,0.007909,0.000445,67.583952,0.015966,0.715008,0.062394,0
1,7010.SR,2023-05-23,35.849648,36.500719,35.727573,36.256567,4356466.0,-0.012332,0.001733,61.832175,0.015774,0.719161,0.060256,0
2,7010.SR,2023-05-24,35.564800,36.175180,35.320649,35.849643,3877533.0,-0.007946,0.003206,58.424550,0.013005,0.728830,0.059794,0
3,7010.SR,2023-05-25,34.710278,35.564809,34.710278,35.564809,5045620.0,-0.024027,0.001296,49.594433,0.012493,0.737809,0.063378,0
4,7010.SR,2023-05-28,33.774357,34.873039,33.611588,34.710274,4954284.0,-0.026964,-0.001491,42.090993,0.013513,0.775212,0.079169,0

In [221]:
X_train_new = X_train_new.drop(columns=["Ticker","Date","Target"])

In [222]:
X_train_new.head()

,Close,High,Low,Open,Volume,Return,ret_14days,RSI,Volatility_std,ATR,BB_width
0,36.297256,36.500716,35.808954,35.890337,3169753.0,0.007909,0.000445,67.583952,0.015966,0.715008,0.062394
1,35.849648,36.500719,35.727573,36.256567,4356466.0,-0.012332,0.001733,61.832175,0.015774,0.719161,0.060256
2,35.564800,36.175180,35.320649,35.849643,3877533.0,-0.007946,0.003206,58.424550,0.013005,0.728830,0.059794
3,34.710278,35.564809,34.710278,35.564809,5045620.0,-0.024027,0.001296,49.594433,0.012493,0.737809,0.063378
4,33.774357,34.873039,33.611588,34.710274,4954284.0,-0.026964,-0.001491,42.090993,0.013513,0.775212,0.079169

In [229]:
X_train.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'Return', 'RSI', 'ret_14days',
       'Volatility_std', 'ATR', 'BB_width'],
      dtype='str')

In [240]:
feature_cols = ['Volume',
 'Return',
 'RSI',
 'ret_14days',
 'Volatility_std',
 'ATR',
 'BB_width']

In [241]:
with open("features_cols.json", "w") as f:
    json.dump(feature_cols,f)